matrix:
  include:
    # Ubuntu 14.04
    - os: linux
      dist: trusty
      sudo: required
      env: CC=gcc-4.9 && CXX=g++-4.9
    # macOS 10.10
    - os: osx
      osx_image: xcode6.4
      before_install:
        - brew update
        - brew install clang
      env: CC=/usr/local/bin/clang && CXX=/usr/local/bin/clang++
    # macOS 10.11
    - os: osx
      osx_image: xcode7.3
      before_install:
        - brew update
        - brew upgrade
      env: CC=/usr/local/bin/gcc && CXX=/usr/local/bin/g++
    # macOS 10.12
    - os: osx
      osx_image: xcode8.3
      env: CXXFLAGS=-g -std=c++11 -Wall -pedantic
    # macOS 10.12
    - os: osx
      osx_image: xcode9.1
      env: CXXFLAGS=-g -std=c++11 -Wall -pedantic
language: node_js
node_js:
  - "8"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install hdf5 --c++11; fi
  - npm install -g npm
  - npm install -g greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
script:
  - npm run build
  - npm test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gfortran
      - cmake
      - libblas-dev
      - libopenblas-dev
      - libhdf5-dev
