version: 0.2.0.{build}
skip_non_tags: false
max_jobs: 1
image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
environment:
  nodejs_version: "8"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install bluebird node-wget-promise fs-extra
  - curl -fsSL https://gist.githubusercontent.com/dasantonym/74a15caa27a93ab20903badba94783b5/raw/mtk-dl-dependencies.js | node -r bluebird
  - npm -g install windows-build-tools
  - npm -g install node-gyp
  - npm -g install mocha
  - npm config set msvs_version 2015 --global
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run build
  - npm test
build: off
